on: [push, pull_request]

jobs:
  test:
    name: make
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: make
        run: make
      - name: add imagediff
        run: sudo sh -c 'wget https://gist.githubusercontent.com/nna774/9b06603599bd26986126af6fa50436f4/raw/1988ea75cbaa494ad1bc96e0d56188d15f04fd6a/imagediff.sh -O /usr/local/bin/imagediff && chmod +x /usr/local/bin/imagediff'
      - name: test
        run: make test
