on: [push, pull_request]

jobs:
  test:
    name: make
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: make
        run: make
      - name: test
        run: make test
